name: english-pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  # ==== Python 환경 ====
  - python=3.10.12
  
  # ==== 기본 빌드 도구 ====
  - pip
  - setuptools
  - wheel
  
  # ==== 시스템 의존성 ====
  - ffmpeg
  
  # ==== Montreal Forced Aligner ====
  - montreal-forced-aligner>=2.2.17
  
  # ==== 수치 계산 ====
  - numpy>=1.24.0
  - scipy>=1.10.0
  - pandas>=2.0.0
  
  # ==== 음성 처리 (conda-forge 우선) ====
  - librosa>=0.10.0
  - soundfile
  - audioread
  - praat-parselmouth>=0.4.0
  
  # ==== 자연어 처리 ====
  - spacy>=3.7.0
  
  # ==== 시각화 (선택사항) ====
  - matplotlib>=3.7.0
  
  # ==== pip로만 설치 가능한 패키지들 ====
  - pip:
    # 웹 프레임워크
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - python-dotenv==1.0.0
    
    # 데이터 검증
    - pydantic==2.11.5
    - pydantic-core==2.33.2
    
    # HTTP 클라이언트
    - httpx==0.25.2
    - aiohttp==3.12.7
    - aiosignal==1.3.2
    - async-timeout==5.0.1
    
    # 데이터베이스
    - motor==3.3.2
    - pymongo==4.6.0
    - pymysql==1.1.0
    
    # AWS
    - boto3==1.34.34
    - botocore==1.34.34
    
    # OpenAI
    - openai==1.12.0
    
    # 음성 처리 (pip 전용)
    - praat-textgrids==1.4.0
    - whisperx==3.3.4
    - pyannote.audio==3.3.2
    - textgrids
    
    # 자연어 처리 
    - benepar==0.2.0
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.8.0/en_core_web_md-3.8.0-py3-none-any.whl 