name: english-fluency-pipeline
channels:
  - conda-forge
  - defaults
dependencies:
  # ==== Python 환경 ====
  - python=3.10.12
  
  # ==== 시스템 빌드 도구 ====
  - pip
  - setuptools
  - wheel
  - cmake
  - gcc_linux-64  # Linux용 (macOS는 자동 처리)
  - gxx_linux-64  # Linux용
  
  # ==== 멀티미디어 시스템 의존성 ====
  - ffmpeg>=6.0
  - sox
  - libsndfile
  - portaudio
  
  # ==== Montreal Forced Aligner (핵심 컴포넌트) ====
  - montreal-forced-aligner>=2.2.17
  - kaldi>=5.5
  - openfst>=1.8.2
  
  # ==== 과학 계산 라이브러리 ====
  - numpy>=1.24.0,<2.0
  - scipy>=1.10.0
  - pandas>=2.0.0
  - scikit-learn>=1.3.0
  
  # ==== 음성/오디오 처리 (conda 최적화) ====
  - librosa>=0.10.0
  - soundfile>=0.12.0
  - audioread>=3.0.0
  - praat-parselmouth>=0.4.3
  - resampy>=0.4.0
  
  # ==== 자연어 처리 ====
  - spacy>=3.7.0
  - nltk>=3.8.0
  
  # ==== 머신러닝 백엔드 ====
  - pytorch>=2.0.0
  - torchvision
  - torchaudio
  - transformers>=4.30.0
  
  # ==== 시각화 및 분석 ====
  - matplotlib>=3.7.0
  - seaborn>=0.12.0
  - plotly>=5.15.0
  
  # ==== 병렬 처리 및 성능 ====
  - joblib>=1.3.0
  - numba>=0.57.0
  - multiprocess>=0.70.0
  
  # ==== 파일 I/O 및 압축 ====
  - h5py>=3.9.0
  - tables>=3.8.0
  - lz4>=4.0.0
  
  # ==== 데이터베이스 지원 ====
  - pymongo>=4.6.0
  - sqlalchemy>=2.0.0
  
  # ==== pip 전용 패키지 (pipeline 특화) ====
  - pip:
    # ==== FastAPI 웹 서버 ====
    - fastapi==0.104.1
    - uvicorn[standard]==0.24.0
    - python-dotenv==1.0.0
    
    # ==== 데이터 검증 ====
    - pydantic==2.11.5
    - pydantic-core==2.33.2
    
    # ==== HTTP 및 비동기 ====
    - httpx==0.25.2
    - aiohttp==3.12.7
    - aiosignal==1.3.2
    - async-timeout==5.0.1
    
    # ==== 데이터베이스 드라이버 ====
    - motor==3.3.2
    - pymysql==1.1.0
    
    # ==== 클라우드 서비스 ====
    - boto3==1.34.34
    - botocore==1.34.34
    
    # ==== AI 서비스 ====
    - openai==1.12.0
    
    # ==== 음성 처리 특화 (pip 전용) ====
    - praat-textgrids==1.4.0
    - textgrids>=1.4.0
    - whisperx==3.3.4
    - pyannote.audio==3.3.2
    - faster-whisper>=0.10.0
    
    # ==== 자연어 처리 특화 ====
    - benepar==0.2.0
    - spacy-transformers>=1.3.0
    
    # ==== Spacy 언어 모델 ====
    - https://github.com/explosion/spacy-models/releases/download/en_core_web_md-3.8.0/en_core_web_md-3.8.0-py3-none-any.whl
    
    # ==== 추가 음성학 도구 ====
    - praatio>=6.0.0
    - phonemizer>=3.2.0
    - webrtcvad>=2.0.10
    
    # ==== 성능 모니터링 ====
    - psutil>=5.9.0
    - memory-profiler>=0.61.0
    
    # ==== 텍스트 그리드 처리 ====
    - pympi-ling>=1.70
    - textgrid>=1.5.0 